### ISSUE TITLE
Choperia Opção

### ISSUE THREAD

**Issue by jroliveira** [beerjs/sp#1]
Olá pessoal, tudo bem?

Estou passando para sugerir um encontro para discutir sobre SPA.
Recentemente eu fui nesta choperia com uns amigos, é um lugar bem legal, 

https://goo.gl/maps/m7KPutvB7bT2

Vamos lá?

**Comment by thebergamo** [comment]
Parece bacana @jroliveira quando vc sugere?

**Comment by jroliveira** [comment]
> Parece bacana @jroliveira quando vc sugere?

Qualquer dia da semana, de preferência não de sexta-feira.

**Comment by thebergamo** [comment]
Blz! Vou criar o evento aqui :)

**Comment by thebergamo** [comment]
hehe melhor @jroliveira manda um PR no readme com as informações do evento ;)
